/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EscalasRouteImport } from './routes/escalas'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as MembrosRouteImport } from './routes/membros'
import { Route as MinhasEscalasRouteImport } from './routes/minhas-escalas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RepertorioRouteImport } from './routes/repertorio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasRoute = EscalasRouteImport.update({
  id: '/escalas',
  path: '/escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const MembrosRoute = MembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasEscalasRoute = MinhasEscalasRouteImport.update({
  id: '/minhas-escalas',
  path: '/minhas-escalas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RepertorioRoute = RepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/entrar': typeof EntrarRoute
  '/escalas': typeof EscalasRoute
  '/grupos': typeof GruposRoute
  '/membros': typeof MembrosRoute
  '/minhas-escalas': typeof MinhasEscalasRoute
  '/relatorios': typeof RelatoriosRoute
  '/repertorio': typeof RepertorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/entrar': typeof EntrarRoute
  '/escalas': typeof EscalasRoute
  '/grupos': typeof GruposRoute
  '/membros': typeof MembrosRoute
  '/minhas-escalas': typeof MinhasEscalasRoute
  '/relatorios': typeof RelatoriosRoute
  '/repertorio': typeof RepertorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convite': typeof ConviteRoute
  '/entrar': typeof EntrarRoute
  '/escalas': typeof EscalasRoute
  '/grupos': typeof GruposRoute
  '/membros': typeof MembrosRoute
  '/minhas-escalas': typeof MinhasEscalasRoute
  '/relatorios': typeof RelatoriosRoute
  '/repertorio': typeof RepertorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convite'
    | '/entrar'
    | '/escalas'
    | '/grupos'
    | '/membros'
    | '/minhas-escalas'
    | '/relatorios'
    | '/repertorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convite'
    | '/entrar'
    | '/escalas'
    | '/grupos'
    | '/membros'
    | '/minhas-escalas'
    | '/relatorios'
    | '/repertorio'
  id:
    | '__root__'
    | '/'
    | '/convite'
    | '/entrar'
    | '/escalas'
    | '/grupos'
    | '/membros'
    | '/minhas-escalas'
    | '/relatorios'
    | '/repertorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConviteRoute: typeof ConviteRoute
  EntrarRoute: typeof EntrarRoute
  EscalasRoute: typeof EscalasRoute
  GruposRoute: typeof GruposRoute
  MembrosRoute: typeof MembrosRoute
  MinhasEscalasRoute: typeof MinhasEscalasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RepertorioRoute: typeof RepertorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas': {
      id: '/escalas'
      path: '/escalas'
      fullPath: '/escalas'
      preLoaderRoute: typeof EscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membros': {
      id: '/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof MembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-escalas': {
      id: '/minhas-escalas'
      path: '/minhas-escalas'
      fullPath: '/minhas-escalas'
      preLoaderRoute: typeof MinhasEscalasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repertorio': {
      id: '/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof RepertorioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConviteRoute: ConviteRoute,
  EntrarRoute: EntrarRoute,
  EscalasRoute: EscalasRoute,
  GruposRoute: GruposRoute,
  MembrosRoute: MembrosRoute,
  MinhasEscalasRoute: MinhasEscalasRoute,
  RelatoriosRoute: RelatoriosRoute,
  RepertorioRoute: RepertorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
